// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class LetscountResources
{
        public const string achievement_suyog_sng = "CgkIoNK4t5MOEAIQCg"; // <GPGSID>
        public const string achievement_shivam_kharga = "CgkIoNK4t5MOEAIQDQ"; // <GPGSID>
        public const string achievement_anish_stha = "CgkIoNK4t5MOEAIQCw"; // <GPGSID>
        public const string achievement_worlds_noobest_player = "CgkIoNK4t5MOEAIQCA"; // <GPGSID>
        public const string achievement_anish_parajuli = "CgkIoNK4t5MOEAIQDA"; // <GPGSID>
        public const string achievement_professional_ball_toucher = "CgkIoNK4t5MOEAIQDg"; // <GPGSID>
        public const string achievement_fastest_fingerer = "CgkIoNK4t5MOEAIQBw"; // <GPGSID>
        public const string achievement_sailesh_mishra = "CgkIoNK4t5MOEAIQCQ"; // <GPGSID>
        public const string leaderboard_global_leaderboard = "CgkIoNK4t5MOEAIQAA"; // <GPGSID>

}

